name: simple_camera
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.10.0"

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation

dependencies:
  camera_android: ^0.10.5
  camera_avfoundation: 0.9.13+1
  camera_platform_interface: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0