name: simple_camera
description: Package for quick and easy use of the camera, you can implement and use the camera in your application in a few steps
version: 1.0.3
repository: https://github.com/mathlouly/simple_camera
issue_tracker: https://github.com/mathlouly/simple_camera/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android: ^0.10.8+15
  camera_avfoundation: ^0.9.13+8
  camera_platform_interface: ^2.7.0
  camera_web: ^0.3.2+3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1