name: simple_camera
description: Package for fast and easy use of the camera
version: 1.0.2
repository: https://github.com/mathlouly/simple_camera
issue_tracker: https://github.com/mathlouly/simple_camera/issues

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation

dependencies:
  camera_android: ^0.10.5
  camera_avfoundation: ^0.9.13+1
  camera_platform_interface: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0